### ISSUE TITLE
MISSING PLACEHOLDER FOR "ENTER YOUR NAME"

### ISSUE THREAD

**Issue by khushiiagrawal** [beachlasagna/IndiGeo#24]
Adding the placeholder would enhance the input field.
i would like to fix it

**Comment by beachlasagna** [comment]
You have been assigned the issue, if possible also try to fix the ui

**Comment by khushiiagrawal** [comment]
yea sure

**Comment by QaisarMoin** [comment]
Please assign me this issue.

**Comment by khushiiagrawal** [comment]
> You have been assigned the issue, if possible also try to fix the ui 
> 
> 

Everything is done. Now you can review the pr and merge it
